import type { Metadata } from "next";
import { Inter,Roboto,Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { ToastContainer, toast } from "./components/toastifty";
import "react-toastify/dist/ReactToastify.css";

const inter = Roboto_Condensed({ subsets: ["cyrillic-ext"] });

export const metadata: Metadata = {
  title: "Next Gallery",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
